/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodolistRouteImport } from './routes/todolist'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestHelloRouteImport } from './routes/test/deadline'

const TodolistRoute = TodolistRouteImport.update({
  id: '/todolist',
  path: '/todolist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestHelloRoute = TestHelloRouteImport.update({
  id: '/test/hello',
  path: '/test/hello',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/todolist': typeof TodolistRoute
  '/test/hello': typeof TestHelloRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todolist': typeof TodolistRoute
  '/test/hello': typeof TestHelloRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/todolist': typeof TodolistRoute
  '/test/hello': typeof TestHelloRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/todolist' | '/test/hello'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/todolist' | '/test/hello'
  id: '__root__' | '/' | '/todolist' | '/test/hello'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TodolistRoute: typeof TodolistRoute
  TestHelloRoute: typeof TestHelloRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todolist': {
      id: '/todolist'
      path: '/todolist'
      fullPath: '/todolist'
      preLoaderRoute: typeof TodolistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/hello': {
      id: '/test/hello'
      path: '/test/hello'
      fullPath: '/test/hello'
      preLoaderRoute: typeof TestHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TodolistRoute: TodolistRoute,
  TestHelloRoute: TestHelloRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
