/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodolistIndexRouteImport } from './routes/todolist/index'
import { Route as TodolistIdRouteImport } from './routes/todolist/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodolistIndexRoute = TodolistIndexRouteImport.update({
  id: '/todolist/',
  path: '/todolist/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodolistIdRoute = TodolistIdRouteImport.update({
  id: '/todolist/$id',
  path: '/todolist/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/todolist/$id': typeof TodolistIdRoute
  '/todolist/': typeof TodolistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/todolist/$id': typeof TodolistIdRoute
  '/todolist': typeof TodolistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/todolist/$id': typeof TodolistIdRoute
  '/todolist/': typeof TodolistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register' | '/todolist/$id' | '/todolist/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/todolist/$id' | '/todolist'
  id: '__root__' | '/' | '/login' | '/register' | '/todolist/$id' | '/todolist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TodolistIdRoute: typeof TodolistIdRoute
  TodolistIndexRoute: typeof TodolistIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todolist/': {
      id: '/todolist/'
      path: '/todolist'
      fullPath: '/todolist/'
      preLoaderRoute: typeof TodolistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todolist/$id': {
      id: '/todolist/$id'
      path: '/todolist/$id'
      fullPath: '/todolist/$id'
      preLoaderRoute: typeof TodolistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TodolistIdRoute: TodolistIdRoute,
  TodolistIndexRoute: TodolistIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
